# Generated by Django 2.0.2 on 2018-03-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField()),
                ('load_value', models.FloatField(null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
